Update blank.yml
commit1

diff --git a/.github/workflows/blank.yml b/.github/workflows/blank.yml
--- a/.github/workflows/blank.yml
+++ b/.github/workflows/blank.yml
@@ -16,7 +16,27 @@ jobs:
       run: |
         apt-get update && apt-get install -y --no-install-recommends wget
         wget --quiet https://github.com/renaissance-benchmarks/renaissance/releases/download/v0.15.0/renaissance-gpl-0.15.0.jar
+   
+    - name: Check if JAR file exists
+      run: |
+        if test -f renaissance-gpl-0.15.0.jar; then
+          echo "JAR file exists."
+        else
+          echo "JAR file not found."
+          exit 1
+        fi
 
+    - name: Check installed packages and their size
+      run: |
+        echo "Number of installed packages: $(dpkg -l | grep ^ii | wc -l)"
+        echo "Installed packages and their sizes:"
+        dpkg-query -Wf '${Installed-Size}\t${Package}\n' | sort -n
+
+    - name: Check installation time of packages
+      run: |
+        echo "Installation time of installed packages:"
+        ls -lt --time=ctime /var/lib/dpkg/info/*.list
+        
   #   - name: Build Java runtime with jlink
   #     run: |
   #       jlink \
