Update blank.yml
temurin

diff --git a/.github/workflows/blank.yml b/.github/workflows/blank.yml
--- a/.github/workflows/blank.yml
+++ b/.github/workflows/blank.yml
@@ -6,81 +6,44 @@ on:
       - main
 
 jobs:
-  test-21-ubuntu:
-    runs-on: ubuntu-latest
-    container:
-      image: mcr.microsoft.com/openjdk/jdk:21-ubuntu
-
-    steps:
-      
-    - name: Install wget and JAR file
-      run: |
-        start_time=$(date +%s)
-        apt-get update && apt-get install -y --no-install-recommends wget
-        wget --quiet https://github.com/renaissance-benchmarks/renaissance/releases/download/v0.15.0/renaissance-gpl-0.15.0.jar
-        end_time=$(date +%s)
-        elapsed_time=$((end_time - start_time))
-        echo "Time taken: $elapsed_time seconds"
-   
-    - name: Check if JAR file exists
-      run: |
-        if test -f renaissance-gpl-0.15.0.jar; then
-          echo "JAR file exists."
-        else
-          echo "JAR file not found."
-          exit 1
-        fi
-
-    - name: Display size of JAR file
-      run: |
-        jar_size_kb=$(du -k renaissance-gpl-0.15.0.jar | cut -f1)
-        echo "Size of JAR file: $jar_size_kb KB"
-
-    - name: Check installed packages (excluding JAR file) and their size
-      run: |
-        num_installed_packages=$(dpkg -l | grep ^ii | grep -v renaissance-gpl-0.15.0.jar | wc -l)
-        echo "Number of installed packages (excluding JAR file): $num_installed_packages"
-
-        installed_packages_size=$(dpkg-query -Wf '${Installed-Size}\n' | grep -v renaissance-gpl-0.15.0.jar | awk '{sum+=$1} END{print sum}')
-        echo "Total size of installed packages (excluding JAR file): $installed_packages_size KB"
-        
-    - name: Build Java runtime with jlink
-      run: |
-        jlink \
-          --add-modules java.base \
-          --strip-debug \
-          --no-man-pages \
-          --no-header-files \
-          --compress=2 \
-          --output /javaruntime
-
-    - name: Set up environment
-      run: |
-        echo "PATH=$PATH:/javaruntime/bin" >> $GITHUB_ENV
-
-    - name: Measure time for running the Renaissance benchmark
-      run: |
-        start_time=$(date +%s)
-        java -jar renaissance-gpl-0.15.0.jar functional
-        end_time=$(date +%s)
-        elapsed_time=$((end_time - start_time))
-        echo "Time taken for running the Renaissance benchmark: $elapsed_time seconds"
-   
-  ## test-eclipse-temurin-21:
+  # test-21-ubuntu:
   #   runs-on: ubuntu-latest
   #   container:
-  #     image: eclipse-temurin:21
+  #     image: mcr.microsoft.com/openjdk/jdk:21-ubuntu
 
   #   steps:
-  #   # - name: Install wget
-  #   #   run: |
-  #   #     apt update
-  #   #     apt install -y wget
-
-  #   - name: Download Renaissance Suite JAR file
+      
+  #   - name: Install wget and JAR file
   #     run: |
-  #       wget https://github.com/renaissance-benchmarks/renaissance/releases/download/v0.15.0/renaissance-gpl-0.15.0.jar -O renaissance-gpl-0.15.0.jar
+  #       start_time=$(date +%s)
+  #       apt-get update && apt-get install -y --no-install-recommends wget
+  #       wget --quiet https://github.com/renaissance-benchmarks/renaissance/releases/download/v0.15.0/renaissance-gpl-0.15.0.jar
+  #       end_time=$(date +%s)
+  #       elapsed_time=$((end_time - start_time))
+  #       echo "Time taken: $elapsed_time seconds"
+   
+  #   - name: Check if JAR file exists
+  #     run: |
+  #       if test -f renaissance-gpl-0.15.0.jar; then
+  #         echo "JAR file exists."
+  #       else
+  #         echo "JAR file not found."
+  #         exit 1
+  #       fi
 
+  #   - name: Display size of JAR file
+  #     run: |
+  #       jar_size_kb=$(du -k renaissance-gpl-0.15.0.jar | cut -f1)
+  #       echo "Size of JAR file: $jar_size_kb KB"
+
+  #   - name: Check installed packages (excluding JAR file) and their size
+  #     run: |
+  #       num_installed_packages=$(dpkg -l | grep ^ii | grep -v renaissance-gpl-0.15.0.jar | wc -l)
+  #       echo "Number of installed packages (excluding JAR file): $num_installed_packages"
+
+  #       installed_packages_size=$(dpkg-query -Wf '${Installed-Size}\n' | grep -v renaissance-gpl-0.15.0.jar | awk '{sum+=$1} END{print sum}')
+  #       echo "Total size of installed packages (excluding JAR file): $installed_packages_size KB"
+        
   #   - name: Build Java runtime with jlink
   #     run: |
   #       jlink \
@@ -95,9 +58,46 @@ jobs:
   #     run: |
   #       echo "PATH=$PATH:/javaruntime/bin" >> $GITHUB_ENV
 
-  #   - name: Run Renaissance benchmark
+  #   - name: Measure time for running the Renaissance benchmark
   #     run: |
+  #       start_time=$(date +%s)
   #       java -jar renaissance-gpl-0.15.0.jar functional
+  #       end_time=$(date +%s)
+  #       elapsed_time=$((end_time - start_time))
+  #       echo "Time taken for running the Renaissance benchmark: $elapsed_time seconds"
+   
+  test-eclipse-temurin-21:
+    runs-on: ubuntu-latest
+    container:
+      image: eclipse-temurin:21
+
+    steps:
+    # - name: Install wget
+    #   run: |
+    #     apt update
+    #     apt install -y wget
+
+    - name: Download Renaissance Suite JAR file
+      run: |
+        wget https://github.com/renaissance-benchmarks/renaissance/releases/download/v0.15.0/renaissance-gpl-0.15.0.jar -O renaissance-gpl-0.15.0.jar
+
+    - name: Build Java runtime with jlink
+      run: |
+        jlink \
+          --add-modules java.base \
+          --strip-debug \
+          --no-man-pages \
+          --no-header-files \
+          --compress=2 \
+          --output /javaruntime
+
+    - name: Set up environment
+      run: |
+        echo "PATH=$PATH:/javaruntime/bin" >> $GITHUB_ENV
+
+    - name: Run Renaissance benchmark
+      run: |
+        java -jar renaissance-gpl-0.15.0.jar functional
            
   # test-eclipse-temurin-21-alpine:
   #   runs-on: ubuntu-latest
