Update blank.yml
17-ubuntu

diff --git a/.github/workflows/blank.yml b/.github/workflows/blank.yml
--- a/.github/workflows/blank.yml
+++ b/.github/workflows/blank.yml
@@ -192,32 +192,93 @@ jobs:
 
 
         
-  test-17-mariner:
+  # test-17-mariner:
+  #   runs-on: ubuntu-latest
+  #   container:
+  #     image: mcr.microsoft.com/openjdk/jdk:17-mariner
+  #   steps:
+  #   - name: Install binutils
+  #     run: |
+  #       curl -sL https://packages.microsoft.com/keys/microsoft.asc | gpg --import -
+  #       yum install -y --setopt install_weak_deps=0 binutils gawk
+  #       # Check the number of installed packages
+  #       num_installed=$(rpm -qa | wc -l)
+  #       echo "Number of installed packages: $num_installed"
+  #       # Check the size of the installed packages in KB
+  #       installed_size=$(rpm -qa --queryformat "%{SIZE}\n" | awk '{s+=$1} END {print s / 1024}')
+  #       echo "Total size of installed packages: $installed_size KB"
+
+  #   - name: Download Renaissance Suite JAR file
+  #     run: |
+  #         curl -O -L https://github.com/renaissance-benchmarks/renaissance/releases/download/v0.15.0/renaissance-gpl-0.15.0.jar
+   
+  #   - name: Verify downloaded file
+  #     run: |
+  #         md5sum renaissance-gpl-0.15.0.jar
+  #         # Check the size of the downloaded JAR file in KB
+  #         jar_size_kb=$(ls -lk renaissance-gpl-0.15.0.jar | awk '{print $5 / 1024}')
+  #         echo "Size of downloaded JAR file: $jar_size_kb KB"
+        
+  #   - name: Build Java runtime with jlink
+  #     run: |
+  #       jlink \
+  #         --add-modules java.base \
+  #         --strip-debug \
+  #         --no-man-pages \
+  #         --no-header-files \
+  #         --compress=2 \
+  #         --output /javaruntime
+
+  #   - name: Set up environment
+  #     run: |
+  #       echo "PATH=$PATH:/javaruntime/bin" >> $GITHUB_ENV
+
+  #   - name: Run Renaissance benchmark
+  #     run: |
+  #       start_time=$(date +%s)
+  #       java -jar renaissance-gpl-0.15.0.jar functional
+  #       end_time=$(date +%s)
+  #       elapsed_time=$((end_time - start_time))
+  #       echo "Time taken for running the Renaissance benchmark: $elapsed_time seconds"
+
+
+
+
+  test-21-ubuntu:
     runs-on: ubuntu-latest
     container:
-      image: mcr.microsoft.com/openjdk/jdk:17-mariner
-    steps:
-    - name: Install binutils
-      run: |
-        # curl -sL https://packages.microsoft.com/keys/microsoft.asc | gpg --import -
-        # yum install -y --setopt install_weak_deps=0 binutils gawk
-        # # Check the number of installed packages
-        # num_installed=$(rpm -qa | wc -l)
-        # echo "Number of installed packages: $num_installed"
-        # # Check the size of the installed packages in KB
-        # installed_size=$(rpm -qa --queryformat "%{SIZE}\n" | awk '{s+=$1} END {print s / 1024}')
-        # echo "Total size of installed packages: $installed_size KB"
+      image: mcr.microsoft.com/openjdk/jdk:17-ubuntu
 
-    - name: Download Renaissance Suite JAR file
+    steps:
+    - name: Install wget and JAR file
       run: |
-          curl -O -L https://github.com/renaissance-benchmarks/renaissance/releases/download/v0.15.0/renaissance-gpl-0.15.0.jar
+        # start_time=$(date +%s)
+        # apt-get update && apt-get install -y --no-install-recommends wget
+        # end_time=$(date +%s)
+        # elapsed_time=$((end_time - start_time))
+        # echo "Time taken: $elapsed_time seconds"
+        wget --quiet https://github.com/renaissance-benchmarks/renaissance/releases/download/v0.15.0/renaissance-gpl-0.15.0.jar
    
-    - name: Verify downloaded file
+    - name: Check if JAR file exists
       run: |
-          md5sum renaissance-gpl-0.15.0.jar
-          # # Check the size of the downloaded JAR file in KB
-          # jar_size_kb=$(ls -lk renaissance-gpl-0.15.0.jar | awk '{print $5 / 1024}')
-          # echo "Size of downloaded JAR file: $jar_size_kb KB"
+        if test -f renaissance-gpl-0.15.0.jar; then
+          echo "JAR file exists."
+        else
+          echo "JAR file not found."
+          exit 1
+        fi
+
+    - name: Display size of JAR file
+      run: |
+        jar_size_kb=$(du -k renaissance-gpl-0.15.0.jar | cut -f1)
+        echo "Size of JAR file: $jar_size_kb KB"
+
+    - name: Check installed packages (excluding JAR file) and their size
+      run: |
+        num_installed_packages=$(dpkg -l | grep ^ii | wc -l)
+        echo "Number of installed packages (excluding JAR file): $num_installed_packages"
+        installed_packages_size=$(dpkg-query -Wf '${Installed-Size}\n' | awk '{sum+=$1} END{print sum}')
+        echo "Total size of installed packages (excluding JAR file): $installed_packages_size KB"
         
     - name: Build Java runtime with jlink
       run: |
@@ -233,7 +294,7 @@ jobs:
       run: |
         echo "PATH=$PATH:/javaruntime/bin" >> $GITHUB_ENV
 
-    - name: Run Renaissance benchmark
+    - name: Measure time for running the Renaissance benchmark
       run: |
         start_time=$(date +%s)
         java -jar renaissance-gpl-0.15.0.jar functional
